//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanardConfit.NINA.BahtiFocus.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale_fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanardConfit.NINA.BahtiFocus.Locale.Locale.fr-FR", typeof(Locale_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrés.
        /// </summary>
        internal static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de mise au point absolute.
        /// </summary>
        internal static string LblAbsoluteFocusError {
            get {
                return ResourceManager.GetString("LblAbsoluteFocusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La capture d&apos;image a échoué. Réessayer....
        /// </summary>
        internal static string LblCaptureImageFailed {
            get {
                return ResourceManager.GetString("LblCaptureImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturer une nouvelle image pour résoudre....
        /// </summary>
        internal static string LblCaptureImageToSolve {
            get {
                return ResourceManager.GetString("LblCaptureImageToSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise au point critique.
        /// </summary>
        internal static string LblCriticalFocus {
            get {
                return ResourceManager.GetString("LblCriticalFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de l&apos;analyseur de Bachtinov - {0}.
        /// </summary>
        internal static string LblError {
            get {
                return ResourceManager.GetString("LblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branchez la roue filtrante ou effacez la sélection du filtre!.
        /// </summary>
        internal static string LblFilterWheelTips {
            get {
                return ResourceManager.GetString("LblFilterWheelTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de mise au point.
        /// </summary>
        internal static string LblFocusError {
            get {
                return ResourceManager.GetString("LblFocusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle des lignes.
        /// </summary>
        internal static string LblLineAngle {
            get {
                return ResourceManager.GetString("LblLineAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle du masque.
        /// </summary>
        internal static string LblMaskAngle {
            get {
                return ResourceManager.GetString("LblMaskAngle", resourceCulture);
            }
        }
    }
}
